name: FTP Deploy and Setup

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to FTP server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5 
      with:
        local-dir: ./ # or specify your directory if different
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        remote-dir: /www/html/real-state-backend

    - name: SSH commands
      uses: appleboy/ssh-action@v1.0.3 # Use 'latest' or specify the latest version from the GitHub page
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd /www/html/real-state-backend
          npm install
          pm2 restart 7
